### ISSUE TITLE
Web studio faile to clone with 'Uncaught (in promise) QuotaExceededError'

### ISSUE THREAD

**Issue by ra-coder** [stoplightio/studio#224]
VM115:1 Uncaught TypeError: Cannot read property 'isProbablyReaderable' of undefined
    at <anonymous>:1:21

Uncaught (in promise) QuotaExceededError
at ls.onReturn (https://stoplight.io/p/_next/static/chunks/45.b5eef87568786a869027.js:12:107453)
    at Worker.<anonymous> (https://stoplight.io/p/_next/static/chunks/45.b5eef87568786a869027.js:12:105494)
    at Worker.r (https://stoplight.io/p/_next/static/8df2fe1ad1802c5f9e9bc14785b3102d1a52e6e9/pages/_app.js:1:171481)

**Comment by philsturgeon** [comment]
Try it again, lots of performance improvements were made since this was reported.
